const obj = {
  FulfillmentPartnerCode: 'ASSA-AlarmControls',
  Manufacturer: 'Alarm Controls',
  'Primary SKU': 'x',
  IsPrimary: true,
  VisibleOnStoreFront: true,
  SKU: 'TS-2',
  ManufacturerPartNumber: 'TS-2',
  UPC: '',
  'Part #': '',
  Variants: '',
  'Product Name': 'Alarm Controls TS-2, SPDT Contact, Push Button',
  Description: 'The TS-2 request to exit station, with square push button, provides a convenient way to add authorized access control to a variety of applications.',
  Category: 'Category Name: Electronic Access Control,Category Path:/electronic-access-control/|Category Name: Push Buttons & Keyswitches,Category Path:/electronic-access-control/push-buttons-keyswitches/',
  'Product Image': 'https://cdn11.bigcommerce.com/s-y7rgqxv8v9/products/1475/images/7511/28298__23150.1646379428.1280.1280.png?c=1',
  'Variant Image': '',
  ProductPDF: 'https://cbdigitaletl-prod.s3.amazonaws.com/products-pdf/28298_10_TS-60.pdf',
  Inventory: 10000,
  ListPrice: 64,
  SellingPriceAnonymous: 41.6,
  Cost: 26.56,
  Unpublish: '',
  ShippingGroup: 'Hardware',
  LeadTime: 2,
  DisplayOrder: 0,
  Prop65Text: 'Nickel',
  IsWoodDoorProduct: 'FALSE',
  'CB Store': true,
  'HC Store': true,
  Weight: 0,
  Height: 0,
  Length: 0,
  Width: 0,
  'Attribute_Hardware Finish': 'Satin Stainless Steel 654',
  Attribute_Color: 'Green',
  Attribute_Function: '',
  Attribute_Application: 'For Access Control Systems, Electro-Magnetic Locks, Exit REX',
  'Attribute_Duty Weight/Class': '',
  Attribute_Type: 'Square Illuminated Button',
  'Attribute_Device Type': '',
  Attribute_Action: '',
  'Attribute_Additional Information': '',
  Attribute_Anchors: '',
  'Attribute_Arm Type': '',
  'Attribute_Cylinder Type': '',
  'Attribute_ADA Compliant': '',
  'Attribute_NDAA Compliant': '',
  'Attribute_BAA Compliant': '',
  'Attribute_Country of Origin': '',
  'Attribute_Back Check': '',
  Attribute_Backset: '',
  Attribute_Battery: '',
  'Attribute_Bearing Type': '',
  Attribute_Bolt: '',
  'Attribute_Bolt Throw Length': '',
  'Attribute_Through Bolts': '',
  'Attribute_Burglar Rated': '',
  'Attribute_Button Illumination': '',
  'Attribute_Button Text': 'Push to Exit',
  'Attribute_Buzzer Frequency': '',
  'Attribute_Closer Reinforcement': '',
  'Attribute_Closer Size': '',
  'Attribute_Cold Weather Fluid': '',
  Attribute_Communication: '',
  'Attribute_Configuration/Connectors': 'Screw Terminal',
  Attribute_Core: '',
  'Attribute_Corner Type': '',
  Attribute_Cover: '',
  'Attribute_Degree Hold Open': '',
  'Attribute_Degree Swing': '',
  Attribute_Delay: '',
  Attribute_Design: '',
  'Attribute_Direction of Swing': '',
  'Attribute_Dogging Options': '',
  'Attribute_Door Gap': '',
  'Attribute_Door/Frame Finish': '',
  Attribute_Veneer: '',
  'Attribute_Door Height': '',
  'Attribute_Door Width': '',
  'Attribute_Door Thickness': '',
  'Attribute_Door Material': '',
  Attribute_Edges: '',
  Attribute_Galvanized: '',
  Attribute_Doors: '',
  'Attribute_Dust Box': '',
  'Attribute_Dynamic Strength': '',
  'Attribute_Static Strength': '',
  'Attribute_Face Shape': '',
  'Attribute_Faceplate Depth': '',
  'Attribute_Faceplate Height': '5"',
  'Attribute_Faceplate Width': '2-3/4 in',
  'Attribute_Faceplate Size': '',
  'Attribute_Failure Mode': '',
  'Attribute_Frame Application': '',
  'Attribute_Frame Height': '',
  'Attribute_Frame Width': '',
  'Attribute_Frame Head': '',
  'Attribute_Frame Opening': '',
  'Attribute_Frame Type': '',
  'Attribute_Welded Frame': '',
  Attribute_Gauge: '',
  Attribute_Grade: '',
  Attribute_Hand: '',
  'Attribute_Handle Type': '',
  'Attribute_Lever/Knob Design': '',
  'Attribute_Hinge Prep': '',
  'Attribute_Hinge Type': '',
  Attribute_Knuckles: '',
  'Attribute_Tip Style': '',
  'Attribute_Pin Type': '',
  'Attribute_Pivot Type': '',
  'Attribute_Hold Open': '',
  'Attribute_Holding Force': '',
  Attribute_Includes: 'Face Plate',
  Attribute_Trim: '',
  Attribute_Insert: '',
  'Attribute_Jamb Depth/Wall': '',
  'Attribute_Keeper Size': '',
  'Attribute_Keypad Type': '',
  Attribute_Keying: '',
  Attribute_Keys: '',
  Attribute_Cylinder: '',
  Attribute_Keyway: '',
  'Attribute_Number of Pins': '',
  'Attribute_Latch Number': '',
  'Attribute_Latch Type': '',
  Attribute_Lights: '',
  'Attribute_Lock Chassis': '',
  'Attribute_Lock Face Size': '',
  'Attribute_Lock Prep': '',
  Attribute_Magnet: '',
  'Attribute_Manufacturer Hinge and Strike Locations': '',
  Attribute_Material: '430 Stainless Steel',
  'Attribute_Mounting Location': '',
  'Attribute_Mounting Style': '',
  'Attribute_Operating Temperature': '15 to 120 degrees F',
  'Attribute_Pre Load': '',
  Attribute_Prefinished: '',
  'Attribute_Prefit & Premachined': '',
  'Attribute_Programmer/Programming': '',
  'Attribute_Reader Technology': '',
  Attribute_Relay: '',
  Attribute_Reveal: '',
  Attribute_Reversible: '',
  'Attribute_Rose/Escutcheon Size': '',
  'Attribute_Rose/Escutcheon Design': '',
  Attribute_Fasteners: '',
  Attribute_Screws: '',
  Attribute_Series: '',
  Attribute_Projection: '',
  'Attribute_Armature Size': '',
  Attribute_Size: '2" Square Button',
  'Attribute_Metric Size': '',
  'Attribute_Device Length': '',
  Attribute_Depth: '2-1/4 in Behind Plate',
  Attribute_Length: '',
  Attribute_Width: '',
  Attribute_Height: '',
  Attribute_Capacity: '',
  Attribute_Thickness: '',
  Attribute_Weight: '',
  Attribute_Software: '',
  'Attribute_Rust Inhibitor': '',
  Attribute_Standards: 'UL 294 Listed',
  'Attribute_Fire Rated': '',
  'Attribute_Rated Opening Compliant': '',
  Attribute_Stiles: '',
  Attribute_Stop: '',
  Attribute_Strike: '',
  'Attribute_Strike Type': '',
  'Attribute_Strike Size': '',
  'Attribute_Strike Height': '',
  'Attribute_Strike Width': '',
  'Attribute_Strike Number': '',
  'Attribute_Strike Standard': '',
  'Attribute_Strike Bottom': '',
  'Attribute_Strike Top': '',
  Attribute_Thumbturn: '',
  'Attribute_Switch Type': 'Momentary',
  Attribute_Range: '',
  'Attribute_Sold in Pack Size': '',
  Attribute_MOQ: 0,
  'Attribute_Unit of Measure': 'Each',
  'Attribute_Use With': '',
  'Attribute_Number of Users': '',
  'Attribute_Door Release': '',
  Attribute_Power: '',
  'Attribute_Power Transfer/Wires': '',
  'Attribute_Electric Options': '',
  'Attribute_Current Draw': '',
  'Attribute_Current Rating': '',
  'Attribute_Input Current': '',
  'Attribute_Output Current': '',
  'Attribute_Electrical Rating': '12-24 VAC/DC',
  'Attribute_Operating Voltage': '',
  Attribute_Voltage: '',
  'Attribute_Input Voltage': '',
  'Attribute_Output Voltage': '',
  'Attribute_Voltage Rating': '',
  'Attribute_Contact Rating': '10 A @ 35 VDC',
  'Attribute_Volts/Amps': '',
  'Attribute_Amp Draw': '',
  Attribute_Frequency: '',
  'Attribute_Contact Type': 'SPDT',
  'Attribute_Number of Gang': '',
  'Attribute_Wire Required': '',
  'Attribute_Alarm/Siren': '',
  Attribute_Audio: '',
  Attribute_Resolution: '',
  'Attribute_Frame Rate': '',
  'Attribute_Video Compression': '',
  'Attribute_Video Stream': '',
  Attribute_Memory: '',
  Attribute_Lens: '',
  Attribute_Ports: '',
  Attribute_Warranty: 'Limited Lifetime'
};

// const attributesArray = Object.entries(obj)
//   .filter(([key, value]) => key.startsWith('Attribute_') && value !== '')
//   .map(([key, value]) => ({ [key]: value }));

// console.log(attributesArray);

const customFields = Object.entries(obj)
  .filter(([key, value]) => key.startsWith('Attribute_') && value !== '')
  .map(([key, value]) => ({ name: key, value }));

console.log(customFields);

